      *=================================================
      * BORRA LOS CAMPOS UTILIZADOS EN PANTALLA
      *-------------------------------------------------
       BORRA.
           DISPLAY SPACES LINE TAB-LIN(SW3) POSITION TAB-COL(SW3)
                          SIZE TAB-SIZ(SW3).
      *-------------------------------------------------
      * SISTEMA: -GESTION COMERCIAL- (BORRA CAMPOS)
      * NOMBRE RUTINA: BORRA.PRO
      * VERSION: 001    FECHA: JUL'90
