
      *   RUT2.CBL       
      *-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
      * PARA F.JOSE SCARAZZINI 8 LIN-10 - VIOLLAZ
      *-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
      *     IF Y = 2
      *  FALTA AGREGAR RENGLONES
      *-=-=-=-=-=PARA GRANTON 8 LIN-10 =-=-=-=-=-=-=-=-=
      *     WRITE LIN-IMP02 FROM LIN-10.
      *     WRITE LIN-IMP02 FROM LIN-10.
      **    WRITE LIN-IMP02 FROM LIN-10.
      *     WRITE LIN-IMP02 FROM LIN-10.
      *     IF Y = 4 OR Y = 5
      *         WRITE LIN-IMP02 FROM TIT0-0
      *         ELSE WRITE LIN-IMP02 FROM LIN-10.
      *     WRITE LIN-IMP02 FROM LIN-10.
      *     WRITE LIN-IMP02 FROM LIN-10.
      *     WRITE LIN-IMP02 FROM LIN-10.
      *     WRITE LIN-IMP02 FROM LIN-10.
      *     WRITE LIN-IMP02 FROM TIT1-1.
      *     WRITE LIN-IMP02 FROM TIT1-2.
      *     WRITE LIN-IMP02 FROM TIT1-3.
      *     WRITE LIN-IMP02 FROM TIT1-4.
      *     WRITE LIN-IMP02 FROM LIN-10.
      **      ADD 14 TO CONT-R.
      *     ADD 12 TO CONT-R.
      *     WRITE LIN-IMP02 FROM IMP-15.
      *     WRITE LIN-IMP02 FROM IMP-151.
      *     WRITE LIN-IMP02 FROM LIN-10.
      *     ADD 2 TO CONT-R.
      *-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
      * PARA BACCI VICENTE RAMON
      *-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
      *     WRITE LIN-IMP02 FROM LIN-10.
      *     WRITE LIN-IMP02 FROM LIN-10.
      *     WRITE LIN-IMP02 FROM LIN-10.
      *     IF Y = 4 OR Y = 5
      *        WRITE LIN-IMP02 FROM TIT0-0
      *        ELSE WRITE LIN-IMP02 FROM LIN-10.
      *     WRITE LIN-IMP02 FROM LIN-10.
      *     WRITE LIN-IMP02 FROM LIN-10.
      *     WRITE LIN-IMP02 FROM LIN-10.
      *     WRITE LIN-IMP02 FROM LIN-10.
      *     WRITE LIN-IMP02 FROM LIN-10.
      *     WRITE LIN-IMP02 FROM TIT1-1.
      *     WRITE LIN-IMP02 FROM TIT1-2.
      *     WRITE LIN-IMP02 FROM TIT1-3.
      *     WRITE LIN-IMP02 FROM LIN-10.
      *     ADD 13 TO CONT-R.
      *     WRITE LIN-IMP02 FROM LIN-10.      
      *     WRITE LIN-IMP02 FROM IMP-15.
      *     WRITE LIN-IMP02 FROM LIN-10.
      *     ADD 2 TO CONT-R.
      *-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
      * PARA HIERRO SAN JOSE
      *-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
